package sqs.message;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import software.amazon.awssdk.regions.Region;
import software.amazon.awssdk.services.sqs.SqsClient;
import sqs.message.body.UserMessageBody;
import sqs.message.config.SqsConfiguration;
import sqs.message.driver.MessageProducer;

public class App {

    public static void main(String[] args) {
        final String QUEUE_URL = "https://sqs.ap-northeast-1.amazonaws.com/703976800898/test";
        final SqsClient sqs = SqsClient.builder().region(Region.AP_NORTHEAST_1).build();
        final SqsConfiguration config = new SqsConfiguration(sqs, QUEUE_URL);

        final List<String> messages = new ArrayList<String>();
        messages.add(new UserMessageBody("123456", new Date()).toJson());
        messages.add(new UserMessageBody("888888", new Date()).toJson());

        new MessageProducer(config).send(messages);
        sqs.close();
    }
}
